<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Miftahul Hayati Rahmi Putri">
<meta name="dcterms.date" content="2024-01-23">

<title>Pengaruh Tingkat Korupsi terhadap Kemiskinan di Indonesia</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Pengaruh Tingkat Korupsi terhadap Kemiskinan di Indonesia</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Miftahul Hayati Rahmi Putri </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 23, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Salah satu masalah sosial yang menjadi tantangan bangsa Indonesia hingga saat ini adalah kemiskinan. Kemiskinan sendiri bisa disebabkan oleh berbagai faktor, baik internal maupun eksternal, yang berkaitan dengan kondisi ekonomi, sosial, politik, dan budaya. Salah satu contoh faktor eksternal yang menjadi penyebab kemiskinan adalah tindakan korupsi.</p>
<p>Korupsi terjadi ketika individu atau kelompok melakukan penyalahgunaan wewenang untuk kepentingan pribadi maupun kelompoknya sehingga merugikan kepentingan bersama. Beberapa dampak buruk korupsi, seperti kerugian negara, pembangunan terhambat, demokrasi melemah, dan kualitas pelayanan public menurun. Selain itu, korupsi juga bisa memperlebar kesenjangan sosial dan ekonomi, serta menghambat upaya pengentasan kemiskinan.</p>
<p>Indonesia menjadi salah satu negara dengan tingkat korupsi tertinggi. Indonesia menempati posisi ke-110 dari 180 negara dengan skor sebesar 34 dari 100 poin. Skor tersebut menunjukkan bahwa persepsi korupsi di Indonesia semakin memburuk. Selama tahun 2022, di Indonesia telah terjadi kasus korupsi setidaknya 579 kasus dengan jumlah tersangka sebanyak 1.396 orang.</p>
<p>Dari latar belakang di atas, penelitian yang dilakukan peneliti saat ini diharapkan dapat memberi kontribusi bagi pengembangan ilmu pengetahuan, khususnya dalam bidang ekonomi dan sosial, serta memberikan masukan bagi pemerintah dan masyarakat dalam upaya pemberantasan korupsi dan kemiskinan di Indonesia.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Penelitian ini menguji apakah korupsi mempegaruhi kemiskinan di Indonesia dan hubungan tingkat korupsi dan kemiskinan di Indonesia. Data yang digunakan bersumber dari dari Badan Pusat Statistik (BPS) pada tahun 2022. Objek dari penelitian ini sendiri terdiri dari dua variabel, yaitu variabel x berupa tingkat korupsi dan variabel y berupa kemiskinan.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<ol type="a">
<li><p>Apakah tingkat korupsi mempengaruhi kemiskinan di Indonesia ?</p></li>
<li><p>Bagaimana hubungan tingkat korupsi dan kemiskinan di Indonesia ?</p></li>
</ol>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Tujuan penelitian ini untuk mengetahui seberapa besar tingkat korupsi dapat mempengaruhi kemiskinan yang terjadi di Indonesia serta hubungan yang terjadi di antara keduanya. Manfaat dari penelitian ini sendiri untuk memberi gambaran kepada pemerintah dan juga masyarakat dalam rangka membantu upaya pemberantasan korupsi dan kemiskinan di Indonesia.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(writexl)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p><strong>Korupsi</strong></p>
<p>Korupsi merupakan kegiatan pelanggaran hokum yang dapat berupa penggelapan, penyuapan, penipuan, pemerasan, kolusi, nepotisme, dan lain-lain. Korupsi dapat melibatkan individu maupun kelompok dalam suatu jabatan kekuasaan untuk memperoleh keuntungan yang haram atau untuk memperoleh keuntungan pribadi. Beberapa dampak buruk perilaku korupsi adalah kerugian keuangan dan perekonomian negara, terhambatnya pertumbuhan ekonomi, investasi, perdagangan, dan kompetivitas, melemahnya demokrasi hukum, dan tata kelola pemerintahan, serta menurunkan kualitas pelayanan publik.</p>
<p>Dalam pemberantasannya maka diperlukan kerja sama dari berbagai pihak mulai dari pemerintah hingga masyarakat. Beberapa cara yang dapat dilakukan dalam membantu pemberantasan korupsi adalah meningkatkan pendidikan dan kesadaran masyarakat, meningkatkan kapasitas dan kemandirian lembag penegak hukum, meningkatkan transparansi dan akuntabilitas pemerintah, swasta, dan masyarakat, serta meningkatkan efektivitas dan efisiensi pengelolaan keuangan negara dan perekonomian negara.</p>
<p><strong>Kemiskinan</strong></p>
<p>Kemiskinan merupakan kondisi di mana seseorang tidak dapan memenuhi kebutuhan primernya. Salah satu penyebab kemiskinan adalah korupsi yang dilakukan oleh pihak yang memiliki kekuasaan dan wewenang. Berbagai dampak negatif dari kemiskinan bisa terjadi dalam berbagai bidang, baik kesehatan, pendidikan, pembangunan, dan masih banyak lagi. Kemiskinan yang terjadi dapat menyebabkan berbagai kerugian untuk sebuah negara. Salah satu kerugian yang terjadi akibat adanya korupsi adalah sumber daya manusia yang rendah. Dengan tinggi angka kemiskinan yang terjadi, maka bisa saja sumber daya manusia akan semakin rendah. Oleh karena itu, maka diperlukan tindakan cepat dalam menanggulangi kemiskinan dalam suatu negara.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>Provinsi</th>
<th>korp</th>
<th>kms</th>
<th>x</th>
<th>y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>Aceh</td>
<td>14,45</td>
<td>14,75</td>
<td>1,159867847</td>
<td>1,16879202</td>
</tr>
<tr class="even">
<td>2</td>
<td>Sumatera Utara</td>
<td>8,15</td>
<td>8,03</td>
<td>0,911157609</td>
<td>0,904715545</td>
</tr>
<tr class="odd">
<td>3</td>
<td>Sumatera Barat</td>
<td>5,95</td>
<td>7,23</td>
<td>0,774516966</td>
<td>0,859138297</td>
</tr>
<tr class="even">
<td>4</td>
<td>Riau</td>
<td>6,68</td>
<td>6,65</td>
<td>0,824776462</td>
<td>0,822821645</td>
</tr>
<tr class="odd">
<td>5</td>
<td>Jambi</td>
<td>7,58</td>
<td>6,28</td>
<td>0,879669206</td>
<td>0,797959644</td>
</tr>
<tr class="even">
<td>6</td>
<td>Sumatera Selatan</td>
<td>11,78</td>
<td>12,21</td>
<td>1,07114529</td>
<td>1,086715664</td>
</tr>
<tr class="odd">
<td>7</td>
<td>Bengkulu</td>
<td>14,04</td>
<td>14,34</td>
<td>1,147367108</td>
<td>1,156549151</td>
</tr>
<tr class="even">
<td>8</td>
<td>Lampung</td>
<td>11,11</td>
<td>12,65</td>
<td>1,045714059</td>
<td>1,102090526</td>
</tr>
<tr class="odd">
<td>9</td>
<td>Kep. Bangka Belitung</td>
<td>4,52</td>
<td>5,85</td>
<td>0,655138435</td>
<td>0,767155866</td>
</tr>
<tr class="even">
<td>10</td>
<td>Kep. Riau</td>
<td>5,69</td>
<td>10,69</td>
<td>0,755112266</td>
<td>1,028977705</td>
</tr>
<tr class="odd">
<td>11</td>
<td>DKI Jakarta</td>
<td>4,44</td>
<td>4,44</td>
<td>0,64738297</td>
<td>0,64738297</td>
</tr>
<tr class="even">
<td>12</td>
<td>Jawa Barat</td>
<td>7,62</td>
<td>9,3</td>
<td>0,881954971</td>
<td>0,968482949</td>
</tr>
<tr class="odd">
<td>13</td>
<td>Jawa Tengah</td>
<td>10,77</td>
<td>11,87</td>
<td>1,032215703</td>
<td>1,074450719</td>
</tr>
<tr class="even">
<td>14</td>
<td>DI Yogyakarta</td>
<td>11,04</td>
<td>13,36</td>
<td>1,042969073</td>
<td>1,125806458</td>
</tr>
<tr class="odd">
<td>15</td>
<td>Jawa Timur</td>
<td>10,35</td>
<td>13,98</td>
<td>1,01494035</td>
<td>1,145507171</td>
</tr>
<tr class="even">
<td>16</td>
<td>Banten</td>
<td>6,17</td>
<td>6,79</td>
<td>0,790285164</td>
<td>0,831869774</td>
</tr>
<tr class="odd">
<td>17</td>
<td>Bali</td>
<td>4,25</td>
<td>5,5</td>
<td>0,62838893</td>
<td>0,740362689</td>
</tr>
<tr class="even">
<td>18</td>
<td>Nusa Tenggara Barat</td>
<td>13,85</td>
<td>13,95</td>
<td>1,141449773</td>
<td>1,144574208</td>
</tr>
<tr class="odd">
<td>19</td>
<td>Nusa Tenggara Timur</td>
<td>19,96</td>
<td>23,76</td>
<td>1,300160537</td>
<td>1,375846436</td>
</tr>
<tr class="even">
<td>20</td>
<td>Kalimantan Barat</td>
<td>6,71</td>
<td>8,07</td>
<td>0,82672252</td>
<td>0,906873535</td>
</tr>
<tr class="odd">
<td>21</td>
<td>Kalimantan Tengah</td>
<td>5,11</td>
<td>5,35</td>
<td>0,7084209</td>
<td>0,728353782</td>
</tr>
<tr class="even">
<td>22</td>
<td>Kalimantan Selatan</td>
<td>4,29</td>
<td>4,72</td>
<td>0,632457292</td>
<td>0,673941999</td>
</tr>
<tr class="odd">
<td>23</td>
<td>Kalimantan Timur</td>
<td>6,11</td>
<td>9,28</td>
<td>0,78604121</td>
<td>0,967547976</td>
</tr>
<tr class="even">
<td>24</td>
<td>Kalimantan Utara</td>
<td>6,45</td>
<td>8,74</td>
<td>0,809559715</td>
<td>0,941511433</td>
</tr>
<tr class="odd">
<td>25</td>
<td>Sulawesi Utara</td>
<td>7,38</td>
<td>10,38</td>
<td>0,868056362</td>
<td>1,016197354</td>
</tr>
<tr class="even">
<td>26</td>
<td>Sulawesi Tengah</td>
<td>12,41</td>
<td>14,09</td>
<td>1,093771781</td>
<td>1,148910993</td>
</tr>
<tr class="odd">
<td>27</td>
<td>Sulawesi Selatan</td>
<td>8,7</td>
<td>11,91</td>
<td>0,939519253</td>
<td>1,075911761</td>
</tr>
<tr class="even">
<td>28</td>
<td>Sulawesi Tenggara</td>
<td>11,43</td>
<td>13,94</td>
<td>1,05804623</td>
<td>1,144262774</td>
</tr>
<tr class="odd">
<td>29</td>
<td>Gorontalo</td>
<td>15,15</td>
<td>23,73</td>
<td>1,180412633</td>
<td>1,375297738</td>
</tr>
<tr class="even">
<td>30</td>
<td>Sulawesi Barat</td>
<td>11,49</td>
<td>12,1</td>
<td>1,060320029</td>
<td>1,08278537</td>
</tr>
<tr class="odd">
<td>31</td>
<td>Maluku</td>
<td>16,42</td>
<td>24,64</td>
<td>1,215373153</td>
<td>1,391640703</td>
</tr>
<tr class="even">
<td>32</td>
<td>Maluku Utara</td>
<td>6,46</td>
<td>6,55</td>
<td>0,810232518</td>
<td>0,8162413</td>
</tr>
<tr class="odd">
<td>33</td>
<td>Papua Barat</td>
<td>20,49</td>
<td>29,2</td>
<td>1,311541958</td>
<td>1,465382851</td>
</tr>
<tr class="even">
<td>34</td>
<td>Papua</td>
<td>26,03</td>
<td>34,49</td>
<td>1,415474168</td>
<td>1,537693194</td>
</tr>
</tbody>
</table>
<p>Data diambil dari Badan Pusat Statistik Indonesia tahun 2022 dalam satuan persen. Kemudian peneliti mengolah data dengan melakukan log pada kedua data dan menghasilkan objek data berupa y dari data tingkat kemiskinan (kms), dan x dari data tingkat korupsi(korp). Data yang telah diolah yang akan digunakan sebagai objek dalam penelitian ini.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#import dataset</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>korp<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">'korp.xlsx'</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(korp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 5
  Provinsi         x     y      logx  logy
  &lt;chr&gt;            &lt;chr&gt; &lt;chr&gt; &lt;dbl&gt; &lt;dbl&gt;
1 Aceh             14.45 14,75 1.16  1.17 
2 Sumatera Utara   8,15  8,03  0.911 0.905
3 Sumatera Barat   5,95  7,23  0.775 0.859
4 Riau             6,68  6,65  0.825 0.823
5 Jambi            7,58  6,28  0.880 0.798
6 Sumatera Selatan 11,78 12,21 1.07  1.09 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>korp,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"orange"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"hubunga tingkat korupsi terhadap kemiskinan"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"korupsi"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"kemiskinan"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"sumber: Badan Pusat Statistik"</span>)<span class="sc">+</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode analisis</h3>
<p>Dalam penelitian ini peneliti menggunakan metode regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini dimaksudkan untuk mengetahui seberapa besar pengaruh Tingkat korupsi terhadap kemiskinan di Indonesia. Spesifikasi yang dilakukan sebagai berikut:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t
\]</span> di mana <span class="math inline">\(y_t\)</span> adalah kemiskinan dan <span class="math inline">\(x_t\)</span> adalah tingkat korupsi.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Hasil</p>
<table class="table">
<thead>
<tr class="header">
<th>Coefficients</th>
<th>Estimate</th>
<th>Pr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>0.05201</td>
<td>0.388</td>
</tr>
<tr class="even">
<td>x</td>
<td>1.02687</td>
<td>&lt;2e-16</td>
</tr>
</tbody>
</table>
<p>Kemudian peneliti memasukkan output di atas ke dalam rumus persamaan sehingga:</p>
<p><span class="math display">\[
y_{t}=\ 0.05201 + \ 1.02687x_t+\mu_t
\]</span></p>
<p>Maka dapat diketahui bahwa untuk setiap kenaikan satu unit x, y akan meningkat sebesar 1.02687, hal ini dapat dilihat dari koefisien x sebesar 1.02687. Koefisien regresi untuk x juga sangat signifikan secara statistik, yang berarti bahwa ada hubungan yang kuat antara x dan y. Untuk koefisien intercept sebesar 0.05201, yang berarti jika x bernilai nol, y akan bernilai 0.05201. Namun, koefisien ini tidak signifikan secara statistik pada tingkat 0.05</p>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>korp<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"korp.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>reg<span class="ot">&lt;-</span><span class="fu">lm</span>(logy<span class="sc">~</span>logx,<span class="at">data=</span>korp)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = logy ~ logx, data = korp)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.157351 -0.061623  0.002809  0.047187  0.201570 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.05201    0.05942   0.875    0.388    
logx         1.02687    0.06091  16.858   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.07338 on 33 degrees of freedom
Multiple R-squared:  0.896, Adjusted R-squared:  0.8928 
F-statistic: 284.2 on 1 and 33 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>korp<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(korp<span class="sc">$</span>logy,korp<span class="sc">$</span>m,<span class="at">xlab =</span> <span class="st">"kemiskinan"</span>,<span class="at">ylab =</span> <span class="st">"error"</span>,<span class="at">col=</span><span class="st">'purple'</span>)</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>korp<span class="sc">$</span>m<span class="ot">&lt;-</span><span class="fu">resid</span>(reg)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(korp<span class="sc">$</span>logx,korp<span class="sc">$</span>m,<span class="at">xlab =</span> <span class="st">"tingkat korupsi"</span>,<span class="at">ylab =</span> <span class="st">"error"</span>,<span class="at">col=</span><span class="st">'coral'</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Nilai dari Multiple R-squared tinggi sebesar 0.896, menunjukkan bahwa model ini dapat menjelaskan sekitar 89,6 % variasi dari y. Model memiliki F-statistic yang besar (284.2) dan p-value yang sangat kecil (&lt; 2.2e-16), yang menunjukkan bahwa model ini secara keseluruhan signifikan secara statistik, yaitu ada hubungan linier antara x dan y.</p>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Hasil peneltian menunjukkan adanya pengaruh yang signifikan antara korupsi terhadap kemiskinan, maka semakin meningkatnya korupsi di Indonesia maka akan semakin meningkat pula kemiskinan di Indonesia. Selain itu korupsi juga mampu merusak tatanan demokrasi Indonesia , menurunkan investasi, menciptakan ketidakadilan pendapatan. Sehingga akan berpengaruh buruk pada pertumbuhan ekonomi negara. Pemerintah sangat diperlukan untuk memperhatikan kerugian Indonesia akibat korupsi, maka pemerintah dapat meningkatkan sistem pengawasan, penegakan hukum, selain itu partisipasi masyarakat dalam pemberantasan korupsi.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>Samputra, P. L., &amp; Munandar, A. I. (2019). Korupsi, Indikator Makro Ekonomi, dan IPM terhadap Tingkat Kemiskinan di Indonesia. Jurnal Ekonomi Kuantitatif Terapan.</p>
<p>Khasanah, L. (2021). Dampak Ketimpangan Pendapatan, Tata Kelola Pemerintahan dan Korupsi terhadap Tingkat Kemiskinan di Indonesia. Bharanomics, 1(2), 75-81.</p>
<p>Junaidi, J. (2018). Korupsi, pertumbuhan ekonomi dan kemiskinan di Indonesia. Efritadewi, A., &amp; Adha, A. Z. (2023). KAJIAN ANALISIS TERHADAP DAMPAK KORUPSI DALAM BIDANG PEREKONOMIAN SOSIAL DAN KEMISKINAN SERTA UPAYA PEMBERANTASAN TINDAK PIDANA KORUPSI DI INDONESIA. Causa: Jurnal Hukum dan Kewarganegaraan, 1(7), 41-50.</p>
<p>Gunawan, H. Dampak Korupsi terhadap Pertumbuhan Ekonomi, Ketimpangan Pendapatan, dan Kemiskinan di Indonesia (Doctoral dissertation, IPB University).</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>